public with sharing class Car {

    private String tipo;
    private String cor;
    private String placa;
    private String numeroPortas;
    
    public Car(String pTipo, String pCor, String pPlaca, String pNumeroPortas){
        this.tTipo;
        this.cor = pCor;
        this.placa = pPlaca;
        this.numeroPortas = pNumeroPortas;
    }

    public void acelerar(){

        system.debug('Acelerou');

    }
}